name: Garfield-cli

concurrency: 
  group: build_and_deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmmirror.com/
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd docs
          yarn install --production --frozen-lockfile
      - name: Build
        run: |
          cd docs
          yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
